name: "FAP: Build for multiple SDK sources"
run-name: "Build for multiple SDK sources"

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "{owner}/{repo}"
        required: true

permissions:
  packages: write
  contents: read

env:
  FILENAME: build-fap.yaml
  SDK_PATH: ''
  ARTIFACT_NAME: ''
  ARTIFACT_ID: ''
  ARTIFACT_URL: ''
  GH_TOKEN: ${{ github.token }}

jobs:
  ufbt-build-action:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Official dev channel
            sdk-channel: dev
          - name: Unleashed firmware
            sdk-index-url: "DarkFlippers/unleashed-firmware"
            sdk-hw-target: "f7"
    name: 'UFBT: Build for ${{ matrix.name }}'
    steps:
      - name: Print info
        run: |
          echo "echo ::notice file=${{ env.FILENAME }},title=Build::Build FAP ${{ inputs.release_version }}" >> $GITHUB_ENV

      - name: Replace slash with dash
        run: | 
          CLEAN_NAME=$(echo "${{ inputs.release_version }}" | sed 's/\//-/g' | tr '[:upper:]' '[:lower:]')
          echo "ARTIFACT_NAME=${CLEAN_NAME}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.release_version }}
          clean: true
          submodules: true

      - name: Download SDK
        if: ${{ matrix.sdk-index-url }}
        run: |
          echo "Using SDK index URL: ${{ matrix.sdk-index-url }}"
          gh release download --repo "DarkFlippers/unleashed-firmware" \
            --pattern "flipper-z-f7-sdk-unlshd-*.zip" --clobber
          unzip flipper-z-f7-sdk-unlshd-*.zip
          mv flipper-z-f7-sdk-unlshd-* sdk
          echo "SDK_PATH=sdk" >> $GITHUB_ENV

      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        id: build-app
        with:
          sdk-channel: ${{ matrix.sdk-channel }}
          sdk-file: ${{ env.SDK_PATH }}
          sdk-hw-target: ${{ matrix.sdk-hw-target }}

      - name: Upload app artifacts
        id: upload-artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ steps.build-app.outputs.fap-artifacts }}
          overwrite: true
          if-no-files-found: error

      - name: Extract ID and URL
        env:
          ARTIFACT_ID: ${{ steps.upload-artifacts.outputs.artifact_id }}
          ARTIFACT_URL: ${{ steps.upload-artifacts.outputs.artifact_url }}
        run: |
          echo "echo ::notice file=${{ env.FILENAME }},title=Artifact ID::${{ env.ARTIFACT_ID }}" >> $GITHUB_ENV
          echo "echo ::notice file=${{ env.FILENAME }},title=Artifact URL::${{ env.ARTIFACT_URL }}" >> $GITHUB_ENV
